#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        #pose: chop/pose
        #pose2d: chop/ground_pose
        #child_frame_id: chop/base_link
        #parent_frame_id: map
        use_new_coordinates: false
        publish_markers: true
        markers:
            'M1': # the order of point is determined by Optitrack software
                topic_name: M1/point # M1 should be the one near tip
                frame_id: base
                init_pos: [0.0390, 0.00425, 0.3802] # dummy
            'M2': # The middle
                topic_name: M2/point
                frame_id: base
                init_pos: [0.0227, 0.004656, 0.3408] # dummy
            'M3': # The tails
                topic_name: M3/point
                frame_id: base
                init_pos: [0.0392, 0.0046, 0.2158] # dummy
    '2':
        use_new_coordinates: false
        publish_markers: true
        markers:
            'M7': # the order of point is determined by Optitrack software
                topic_name: M7/point # should be the alone point on rigid body tracker
                frame_id: base
                init_pos: [0.0390, 0.00425, 0.3802] # dummy
            'M8': # The middle
                topic_name: M8/point
                frame_id: base
                init_pos: [0.0227, 0.004656, 0.3408] # dummy
            'M9': # The tails
                topic_name: M9/point
                frame_id: base
                init_pos: [0.0392, 0.0046, 0.2158] # dummy
markers:
    'M4': # this has been modified, the original value is [0.0, 0.0, 0.0]
        topic_name: M4/point
        frame_id: base
        init_pos:  [0.297, -0.004982, 0.376] # Note this is in optitrack frame, look up the coordinate in Motive Software.
    'M5': # this has been modified, the original value is [0.0, 0.005, 0.06]
        topic_name: M5/point
        frame_id: base
        init_pos:  [0.4966, 0.00, 0.381]
    'M6': # this is the marker to pick up
        topic_name: M6/point
        frame_id: base
        init_pos: [0.6175, 0.00, 0.233]

optitrack_config:
        multicast_address: 224.0.0.1
