#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    # MATCH the order of points to select, when creating rigid body in Optitrack Software !!!
    '1': # the end effector tracker
        use_new_coordinates: false
        publish_markers: true
        markers:
            'R0': # the point cloest to chopsticks tip
                topic_name: R0/point
                frame_id: base
                init_pos: [.0, .0, .0] # dummy
            'R1': # The middle
                topic_name: R1/point
                frame_id: base
                init_pos: [.0, .0, .0] # dummy
            'R2': # The tails
                topic_name: R2/point
                frame_id: base
                init_pos: [.0, .0, .0] # dummy
        #pose: chop/pose
        #pose2d: chop/ground_pose
        #child_frame_id: chop/base_link
        #parent_frame_id: map
    '2': # the leader chopsticks
        use_new_coordinates: false
        publish_markers: true
        markers:
            'T0':
                topic_name: T0/point # should be the one near tip
                frame_id: base
                init_pos: [.0, .0, .0] # dummy
            'T1': # The middle
                topic_name: T1/point
                frame_id: base
                init_pos: [.0, .0, .0] # dummy
            'T2': # The tails
                topic_name: T2/point
                frame_id: base
                init_pos: [.0, .0, .0] # dummy
markers:
    # In optitrack frame, look up the coordinate in Motive Software and paste here directly!
    'T3': # the head of the chopsticks that are mounted with two markers
        topic_name: T3/point
        frame_id: base
        init_pos:  [0.58, -0.006, 0.55]
    'T4': # the tail of the chopsticks that are mounted with two markers
        topic_name: T4/point
        frame_id: base
        init_pos:  [0.78, -0.0017, 0.56]
    'Ball': # the marker ball to pick up
        topic_name: Ball/point
        frame_id: base
        init_pos: [0.639, -0.007, 0.311]

optitrack_config:
        multicast_address: 224.0.0.1
