#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        #pose: chop/pose
        #pose2d: chop/ground_pose
        #child_frame_id: chop/base_link
        #parent_frame_id: map
        use_new_coordinates: false
        publish_markers: true
        markers:
            '1': # the order of point is determined by Optitrack software
                topic_name: M1/point # M1 should be the one near tip
                frame_id: map
                init_pos: [-0.05, 0.0, 0.0] # dummy
            '2': # The middle
                topic_name: M2/point
                frame_id: map
                init_pos: [-0.05, 0.0, 0.0] # dummy
            '3': # The tail
                topic_name: M3/point
                frame_id: map
                init_pos: [-0.05, 0.0, 0.0] # dummy
markers:
    'M4': # this has been modified, the original value is [0.0, 0.0, 0.0]
        topic_name: M4/point
        frame_id: map
        init_pos:  [0.02, 0.009, 0.64] # Note this is in optitrack frame, look up the coordinate in Motive Software.
    'M5': # this has been modified, the original value is [0.0, 0.005, 0.06]
        topic_name: M5/point
        frame_id: map
        init_pos:  [0.01, 0.009, 0.845]
#    'M6': # this is the marker to pick up
#        topic_name: M6/point
#        frame_id: map
#        init_pos:  [0.0, 0.0046, 0.268] # Todo: wait to be defined

optitrack_config:
        multicast_address: 224.0.0.1
